version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 9_{hdKc]K<sS'7SL
      MONGO_INITDB_DATABASE: test
      MONGODB_USER: "anuchit"
      MONGODB_DATABASE: "test"
      MONGODB_PASS: "$$test$$"
    volumes: 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 9_{hdKc]K<sS'7SL
  # go-docker-image:
  #   build: ./
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./:/app